name: pinpoint
description: Gather location data for GEOFENCING and IPS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  geolocator: ^9.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.2.0
  uuid: ^3.0.7
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  freezed: ^2.1.1

flutter:
  uses-material-design: true